### ISSUE TITLE
Could one 'query' work items while connected anonymously?

### ISSUE THREAD

**Issue by Ayanmullick** [StartAutomating/PSDevOps#101]
Running `Connect-ADO -Organization ayn` without credentials or PAT looks like it connected successfully. However, `Get-ADOWorkItem -Organization ayn -Project PowerShell -Query 'Select [System.ID] from WorkItems'` fails with error below

```
Invoke-ADORestAPI : Response was HTML, Request Failed.
At C:\Users\ayan\Documents\PowerShell\Modules\psdevops\0.5.3\Get-ADOWorkItem.ps1:240 char:29
+             $queryResults = Invoke-ADORestAPI @invokeParams |
+                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (
<!DOCTYPE h...ody>
</html>
:String) [Invoke-ADORestAPI], Exception
    + FullyQualifiedErrorId : ResultWasHTML,Invoke-ADORestAPI
```

...even though this is a public project and accessible online without authentication. PFB link
https://dev.azure.com/ayn/PowerShell/_workitems

When I `Connect-ADO` with a PAT it works fine. Is there a way to connect anonymously like on can thru the browser, or does one need to log in even for public projects?

**Comment by StartAutomating** [comment]
While I _could_ let Connect-ADO work without a -PAT, I don't think I should;  too much of Azure DevOps uses PATs in subtle ways.

This is a great example.

With a public project, I _can_ get a given work item by -ID without a PAT.
I _cannot_ query work items without a PAT.

Let me know if this makes enough sense and you'd prefer me to close it, or if you'd prefer Connect-ADO to allow you to not pass a -PersonalAccessToken.

**Comment by Ayanmullick** [comment]
@StartAutomating, I would like PowerShell to have parity with the browser. I feel, what's anonymously queryable thru the browser should be thru PowerShell too.

**Comment by StartAutomating** [comment]
@Ayanmullick 

> I would like PowerShell to have parity with the browser. I feel, what's anonymously queryable thru the browser should be thru PowerShell too.

1. This isn't something Azure DevOps makes clear (where the line is between public/private)
2. If the API allows anonymous use, PSDevOps should return results
3. I'm 99.99% sure that there's no way to query work items in a public project.  If I'm wrong here, can you link me to a project where it's enabled?

Did you want any actual code changes here?

**Comment by Ayanmullick** [comment]
@StartAutomating , I was unable to contact you thru Teams. PFB link to a project with public access enabled.

https://dev.azure.com/ayn/PowerShell

And one can review its work items using link below
https://dev.azure.com/ayn/PowerShell/_workitems/recentlyupdated

And this is the query for that view
```sql
SELECT
    [System.Id],
    [System.WorkItemType],
    [System.Title],
    [System.AssignedTo],
    [System.State],
    [System.AreaPath],
    [System.Tags],
    [System.CommentCount]
FROM workitems
WHERE
    [System.Id] IN (@recentProjectActivity)
    AND [System.TeamProject] = @project
ORDER BY [System.ChangedDate] DESC
```

If it's an API limitation we can close this issue.

**Comment by StartAutomating** [comment]
I can see the project, and I can see the work items.

Attempting to query gets me the same "Response was HTML, request failed"

I had thought that it might be that stored queries would potentially work

~~~PowerShell
Invoke-ADORestAPI -Uri "https://dev.azure.com/{organization}/{project}/_apis/wit/queries?api-version=6.0" -UrlParameter @{"Organization"="ayn";"Project"="PowerShell"}
~~~

However this produced the same results.

So it appears there's really no other way to get a work item in a public project that with an -ID.

Sorry that reaching out on Teams didn't work.  Teams attempted to notify me but I see no past message history.  You're welcome to hit me up on the PowerShell discord if you'd like more context here.
