### ISSUE TITLE
Get-ADOUser Errors out

### ISSUE THREAD

**Issue by ranabanerjee15** [StartAutomating/PSDevOps#127]
Hello PSDevOps Team,

I am Verly glad to find a module to manage Azure DevOps, I am trying to get a list of users at the Org level.

but I am hitting an error while I run the following command. I am running it in `7.2.0-preview.10`. I am successfully connected to the organization by running `Connect-ADO`. and have right privileges too. 

```PowerShell
Get-ADOUser -Organization <my-org-name>
```

**Output:**
![image](https://user-images.githubusercontent.com/33179430/139322609-095250c3-8681-4563-a781-772959966516.png)

Thanks once again for your **AWESOME** work :-)

**Comment by StartAutomating** [comment]
@ranabanerjee15 since I cannot tell you why you did not have access, I'm going to close this issue.
