### ISSUE TITLE
New-GithubAction incorrect name?

### ISSUE THREAD

**Issue by stefanstranger** [StartAutomating/PSDevOps#19]
Hi James,

Isn't the New-GithubAction function creating a Github Workflow instead of an Github Action?

[Github Workflow](https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#about-workflows)

[Github Action](https://help.github.com/en/actions/getting-started-with-github-actions/about-github-actions#about-github-actions)

Shouldn't this function be renamed to New-GithubWorkflow?

/Stefan

**Comment by StartAutomating** [comment]
Hi Stefan,

I believe you are correct.

How does New-GitHubWorkflow sound?

For the directory of steps/components, would you prefer \GitHubWorkflow or \GitHub? (I'm somewhat wary of using GitHub, as I'm uncertain of accidental conflicts)?

**Comment by stefanstranger** [comment]
Hi James,

New-GithubWorkflow sounds fine for me. I would keep the folder name to Github because it can contain components of the Github Workflow.

/Stefan

**Comment by StartAutomating** [comment]
Fixed in #38  (with a very solid once-over on GitHub workflow functionality)
