### ISSUE TITLE
order properties when generating yaml

### ISSUE THREAD

**Issue by bmoore-msft** [StartAutomating/PSDevOps#52]
When generating a yml file for a work flow, order properties logically in terms of the code readability, e.g.

    steps: 
      - name: InstallPester
        shell: pwsh
        env: 
            PesterMaxVersion: ${{secrets.PesterMaxVersion}}
        run: |

shell and env are important metadata that give context to "run" and since run is arbitrarily long, you can easily find the other properties if they come first.

**Comment by StartAutomating** [comment]
Implemented in #53
