### ISSUE TITLE
Add-ADOTeam doesn't seem to work

### ISSUE THREAD

**Issue by chriswelde** [StartAutomating/PSDevOps#54]
Try to add a team to a group. Invoke-ADORestAPI returns:

"Invoke-ADORestAPI : The remote server returned an error: (411) Length Required.
At C:\Users\user\Documents\WindowsPowerShell\Modules\PSDevOps\0.4.5\Add-ADOTeam.ps1:135 char:13
             Invoke-ADORestAPI @invokeParams"

Adding an else clause into Invoke-ADORestAPI with the following line "$WebRequest.ContentLength = 0" seems to fix it.

**Comment by StartAutomating** [comment]
This was fixed in #56
