### ISSUE TITLE
Missing option "includehidden=true" in Get-ADORepository in order to view the Wiki repo(s)

### ISSUE THREAD

**Issue by paulgdunn** [StartAutomating/PSDevOps#66]
In order to see the "hidden" Wiki repo for a project, it could prove useful to have the option to -IncludeHidden for the Get-ADORepository function.

As a workaround, repo that is hidden can be accessed through the REST API:
    $myUri = 'https://dev.azure.com/.../_apis/git/repositories?api-version=6.0&includehidden=true' 
    Invoke-ADORestAPI -Uri $myUri  | Out-GridView

**Comment by StartAutomating** [comment]
Included in Pull Request #68 and integrated into 0.4.9
