### ISSUE TITLE
Get-ADORepository -PullRequestID is not Mandatory

### ISSUE THREAD

**Issue by StartAutomating** [StartAutomating/PSDevOps#99]
This causes an ambiguity between parameter sets which errors out some tests.

@cjboden I'll take care of fixing this (I think your tests didn't end up running it because you wouldn't be able to see repos).  If you end up adding more, make sure each new parameter set has at least one unique "key" parameter that lets PowerShell know which parameter set it could use.

**Comment by cjboden** [comment]
@StartAutomating I see what I did. I'll make sure to keep that in mind for the future! Sorry!

**Comment by StartAutomating** [comment]
No big deal, it's fixed now.
